# Generated by Django 4.2.5 on 2023-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_student_subjectstudent_programstudent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='programstudent',
            constraint=models.UniqueConstraint(fields=('program', 'student'), name='program_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='programsubject',
            constraint=models.UniqueConstraint(fields=('program', 'subject'), name='program_subject_unique'),
        ),
        migrations.AddConstraint(
            model_name='subjectlecturer',
            constraint=models.UniqueConstraint(fields=('subject', 'lecturer'), name='subject_lecturer_unique'),
        ),
        migrations.AddConstraint(
            model_name='subjectstudent',
            constraint=models.UniqueConstraint(fields=('subject', 'student'), name='subject_student_unique'),
        ),
    ]
